const mockupStyles=document.createElement('link');mockupStyles.rel='stylesheet';mockupStyles.href='mockup-fixes.css?v=20260720-3';document.head.appendChild(mockupStyles);
let routes=[];
const grid=document.querySelector('#routeGrid');
const routeDialog=document.querySelector('#routeDialog');
const dialogContent=document.querySelector('#dialogContent');
const legacyTags={sea:['ligurien','gardasee-veneto','apulien','sizilien-ost-sued','rom-sizilien','umbrien-marken'],wine:['toscana-cuore','gardasee-veneto','suedtirol-dolomiten','emilia-romagna','umbrien-marken','apulien'],mountain:['gardasee-veneto','suedtirol-dolomiten'],long:['apulien','sizilien-ost-sued','rom-sizilien']};
const themeMap={sea:['sea','beach'],wine:['wine','culinary'],mountain:['mountain','lake'],long:[]};
async function init(){const routeFiles=['routes.json','routes-01-established.json','routes-02-established.json'];const [routeResponses,editorialResponse]=await Promise.all([Promise.all(routeFiles.map(file=>fetch(file))),fetch('route-editorial.json')]);const blocks=await Promise.all(routeResponses.map(response=>{if(!response.ok)throw new Error(`Routendatei fehlt: ${response.url}`);return response.json()}));const editorial=editorialResponse.ok?await editorialResponse.json():{};routes=blocks.flat().map(route=>({...route,editorial:editorial[route.id]||null}));render(routes)}
function hearts(r){const count=Math.max(0,Math.min(5,Number(r.meta?.hearts||0)));return count?`<span class="route-hearts" aria-label="${count} von 5 Herzen">${'♥'.repeat(count)}${'♡'.repeat(5-count)}</span>`:''}
function render(items){grid.innerHTML=items.map(r=>`<article class="route-card" tabindex="0" data-id="${r.id}"><img src="${r.image}" alt="${r.title}" loading="lazy"><div class="card-copy"><div class="card-eyebrow">${r.eyebrow}</div><h3>${r.title}</h3><div class="card-meta"><span>${r.days}</span><span>${r.region}</span></div>${hearts(r)}</div></article>`).join('');document.querySelectorAll('.route-card').forEach(card=>{card.addEventListener('click',()=>openRoute(card.dataset.id));card.addEventListener('keydown',e=>{if(e.key==='Enter')openRoute(card.dataset.id)})})}
function list(items){return `<ul class="editorial-list">${items.map(item=>`<li>${item}</li>`).join('')}</ul>`}
function openRoute(id){const r=routes.find(x=>x.id===id);if(!r)return;const e=r.editorial||{};dialogContent.innerHTML=`<div class="dialog-hero" style="background-image:url('${r.image}')"><div><p class="kicker">${r.eyebrow}</p><h2>${r.title}</h2><p>${r.days} · ${r.distance}</p>${hearts(r)}</div></div><div class="dialog-body"><p class="dialog-lead">${r.summary}</p>${e.decision?`<section class="decision-box"><p class="section-label">Darum lohnt sich diese Route</p><p>${e.decision}</p></section>`:''}<div class="detail-grid"><div><p class="section-label">Die Route im Überblick</p><div class="stops">${r.stops.map(s=>`<span class="stop">${s}</span>`).join('')}</div>${e.highlights?`<section class="editorial-section"><h3>Was euch auf der Route erwartet</h3>${list(e.highlights)}</section>`:''}${e.taste?`<section class="editorial-section"><h3>Wein, Küche und Spezialitäten</h3>${list(e.taste)}</section>`:''}<section class="editorial-section"><h3>Besondere Abzweigungen</h3>${r.detours.map(d=>`<div class="detour"><h4>${d.title}</h4><p>${d.text}</p></div>`).join('')}</section>${e.camper?`<section class="editorial-section"><h3>Mit dem Wohnmobil</h3><p>${e.camper}</p></section>`:''}${e.connections?`<section class="editorial-section"><h3>So lässt sich die Route erweitern</h3>${list(e.connections)}</section>`:''}</div><aside><div class="source-box"><h4>Die Route in einem Satz</h4><p class="why">${e.decision||r.why}</p><h4>Quellen der Grundroute</h4><a href="${r.source.url}" target="_blank" rel="noopener">${r.source.name} ↗</a><a href="${r.source2.url}" target="_blank" rel="noopener">${r.source2.name} ↗</a></div></aside></div></div>`;routeDialog.showModal()}
function routeMatchesFilter(route,key){if(key==='all')return true;if(key==='long')return legacyTags.long.includes(route.id)||parseInt(route.days,10)>=10;const themes=route.meta?.themes||[];const water=route.meta?.water||[];const landscape=route.meta?.landscape||[];const values=[...themes,...water,...landscape];return legacyTags[key]?.includes(route.id)||themeMap[key].some(tag=>values.includes(tag))}
document.querySelector('#dialogClose').onclick=()=>routeDialog.close();routeDialog.addEventListener('click',e=>{if(e.target===routeDialog)routeDialog.close()});document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));button.classList.add('active');const key=button.dataset.filter;render(routes.filter(r=>routeMatchesFilter(r,key)))}));
const searchDialog=document.querySelector('#searchDialog'),searchInput=document.querySelector('#searchInput'),searchResults=document.querySelector('#searchResults');document.querySelector('#searchButton').onclick=()=>{searchDialog.showModal();setTimeout(()=>searchInput.focus(),100)};document.querySelector('#searchClose').onclick=()=>searchDialog.close();searchInput.addEventListener('input',()=>{const q=searchInput.value.toLowerCase().trim();if(!q){searchResults.innerHTML='';return}const found=routes.filter(r=>JSON.stringify(r).toLowerCase().includes(q));searchResults.innerHTML=found.length?found.map(r=>`<div class="search-result" data-id="${r.id}"><h3>${r.title}</h3><p>${r.region} · ${r.days}</p></div>`).join(''):'<p>Kein Treffer. Vielleicht ist genau das unsere nächste Abzweigung.</p>';document.querySelectorAll('.search-result').forEach(el=>el.onclick=()=>{searchDialog.close();openRoute(el.dataset.id)})});
const drawer=document.querySelector('#menuDrawer'),backdrop=document.querySelector('#drawerBackdrop');function toggleDrawer(open){drawer.classList.toggle('open',open);backdrop.classList.toggle('open',open);drawer.setAttribute('aria-hidden',String(!open))}document.querySelector('#menuButton').onclick=()=>toggleDrawer(true);document.querySelector('#drawerClose').onclick=()=>toggleDrawer(false);backdrop.onclick=()=>toggleDrawer(false);drawer.querySelectorAll('a').forEach(a=>a.onclick=()=>toggleDrawer(false));init().catch(()=>{grid.innerHTML='<p>Die Routen konnten nicht geladen werden.</p>'});