let routes=[];
const grid=document.querySelector('#routeGrid');
const routeDialog=document.querySelector('#routeDialog');
const dialogContent=document.querySelector('#dialogContent');
const tags={sea:['ligurien','gardasee-veneto','apulien','sizilien-ost-sued','rom-sizilien','umbrien-marken'],wine:['toscana-cuore','gardasee-veneto','suedtirol-dolomiten','emilia-romagna','umbrien-marken','apulien'],mountain:['gardasee-veneto','suedtirol-dolomiten'],long:['apulien','sizilien-ost-sued','rom-sizilien']};
async function init(){const response=await fetch('routes.json');routes=await response.json();render(routes)}
function render(items){grid.innerHTML=items.map(r=>`<article class="route-card" tabindex="0" data-id="${r.id}"><img src="${r.image}" alt="${r.title}" loading="lazy"><div class="card-copy"><div class="card-eyebrow">${r.eyebrow}</div><h3>${r.title}</h3><div class="card-meta"><span>${r.days}</span><span>${r.region}</span></div></div></article>`).join('');document.querySelectorAll('.route-card').forEach(card=>{card.addEventListener('click',()=>openRoute(card.dataset.id));card.addEventListener('keydown',e=>{if(e.key==='Enter')openRoute(card.dataset.id)})})}
function openRoute(id){const r=routes.find(x=>x.id===id);if(!r)return;dialogContent.innerHTML=`<div class="dialog-hero" style="background-image:url('${r.image}')"><div><p class="kicker">${r.eyebrow}</p><h2>${r.title}</h2><p>${r.days} · ${r.distance}</p></div></div><div class="dialog-body"><p class="dialog-lead">${r.summary}</p><div class="detail-grid"><div><p class="section-label">Die Grundroute</p><div class="stops">${r.stops.map(s=>`<span class="stop">${s}</span>`).join('')}</div><h3 style="font-family:'Cormorant Garamond',serif;font-size:42px;font-weight:400;margin:55px 0 10px">Incanto-Abzweigungen</h3>${r.detours.map(d=>`<div class="detour"><h4>${d.title}</h4><p>${d.text}</p></div>`).join('')}</div><aside><div class="source-box"><h4>Warum sie zu uns passt</h4><p class="why">${r.why}</p><h4>Quellen der Grundroute</h4><a href="${r.source.url}" target="_blank" rel="noopener">${r.source.name} ↗</a><a href="${r.source2.url}" target="_blank" rel="noopener">${r.source2.name} ↗</a></div></aside></div></div>`;routeDialog.showModal()}
document.querySelector('#dialogClose').onclick=()=>routeDialog.close();routeDialog.addEventListener('click',e=>{if(e.target===routeDialog)routeDialog.close()});document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));button.classList.add('active');const key=button.dataset.filter;render(key==='all'?routes:routes.filter(r=>tags[key].includes(r.id)))}));
const searchDialog=document.querySelector('#searchDialog'),searchInput=document.querySelector('#searchInput'),searchResults=document.querySelector('#searchResults');document.querySelector('#searchButton').onclick=()=>{searchDialog.showModal();setTimeout(()=>searchInput.focus(),100)};document.querySelector('#searchClose').onclick=()=>searchDialog.close();searchInput.addEventListener('input',()=>{const q=searchInput.value.toLowerCase().trim();if(!q){searchResults.innerHTML='';return}const found=routes.filter(r=>JSON.stringify(r).toLowerCase().includes(q));searchResults.innerHTML=found.length?found.map(r=>`<div class="search-result" data-id="${r.id}"><h3>${r.title}</h3><p>${r.region} · ${r.days}</p></div>`).join(''):'<p>Kein Treffer. Vielleicht ist genau das unsere nächste Abzweigung.</p>';document.querySelectorAll('.search-result').forEach(el=>el.onclick=()=>{searchDialog.close();openRoute(el.dataset.id)})});
const drawer=document.querySelector('#menuDrawer'),backdrop=document.querySelector('#drawerBackdrop');function toggleDrawer(open){drawer.classList.toggle('open',open);backdrop.classList.toggle('open',open);drawer.setAttribute('aria-hidden',String(!open))}document.querySelector('#menuButton').onclick=()=>toggleDrawer(true);document.querySelector('#drawerClose').onclick=()=>toggleDrawer(false);backdrop.onclick=()=>toggleDrawer(false);drawer.querySelectorAll('a').forEach(a=>a.onclick=()=>toggleDrawer(false));init().catch(()=>{grid.innerHTML='<p>Die Routen konnten nicht geladen werden.</p>'});