const mockupStyles=document.createElement('link');mockupStyles.rel='stylesheet';mockupStyles.href='mockup-fixes.css?v=20260720-4';document.head.appendChild(mockupStyles);
let routes=[];
const grid=document.querySelector('#routeGrid');
const routeDialog=document.querySelector('#routeDialog');
const dialogContent=document.querySelector('#dialogContent');
const legacyTags={sea:['ligurien','gardasee-veneto','apulien','sizilien-ost-sued','rom-sizilien','umbrien-marken'],wine:['toscana-cuore','gardasee-veneto','suedtirol-dolomiten','emilia-romagna','umbrien-marken','apulien'],mountain:['gardasee-veneto','suedtirol-dolomiten'],long:['apulien','sizilien-ost-sued','rom-sizilien']};
const themeMap={sea:['sea','beach'],wine:['wine','culinary'],mountain:['mountain','lake'],long:[]};
async function init(){const routeFiles=['routes.json','routes-01-established.json','routes-02-established.json'];const detailFiles=['route-details-01.json','route-details-02.json','route-details-03.json','route-details-04.json','route-details-05.json','route-details-06.json'];const [routeResponses,editorialResponse,detailResponses]=await Promise.all([Promise.all(routeFiles.map(file=>fetch(file))),fetch('route-editorial.json'),Promise.all(detailFiles.map(file=>fetch(file)))]);const blocks=await Promise.all(routeResponses.map(response=>{if(!response.ok)throw new Error(`Routendatei fehlt: ${response.url}`);return response.json()}));const editorial=editorialResponse.ok?await editorialResponse.json():{};const detailBlocks=await Promise.all(detailResponses.map(response=>response.ok?response.json():{}));const details=Object.assign({},...detailBlocks);routes=blocks.flat().map(route=>({...route,editorial:editorial[route.id]||null,details:details[route.id]||null}));render(routes)}
function hearts(r){const count=Math.max(0,Math.min(5,Number(r.meta?.hearts||0)));return count?`<span class="route-hearts" aria-label="${count} von 5 Herzen">${'♥'.repeat(count)}${'♡'.repeat(5-count)}</span>`:''}
function render(items){grid.innerHTML=items.map(r=>`<article class="route-card" tabindex="0" data-id="${r.id}"><img src="${r.image}" alt="${r.title}" loading="lazy"><div class="card-copy"><div class="card-eyebrow">${r.eyebrow}</div><h3>${r.title}</h3><div class="card-meta"><span>${r.days}</span><span>${r.region}</span></div>${hearts(r)}</div></article>`).join('');document.querySelectorAll('.route-card').forEach(card=>{card.addEventListener('click',()=>openRoute(card.dataset.id));card.addEventListener('keydown',e=>{if(e.key==='Enter')openRoute(card.dataset.id)})})}
function clean(items){return (Array.isArray(items)?items:[]).filter(item=>item!==undefined&&item!==null&&String(item).trim()!=='')}
function list(items){const entries=clean(items);return entries.length?`<ul class="editorial-list">${entries.map(item=>`<li>${typeof item==='string'?item:(item.text||item.title||item.name||'')}</li>`).join('')}</ul>`:''}
function cardList(items,kind){const entries=clean(items);return `<div class="detail-cards ${kind}">${entries.map(item=>`<article><h4>${item.name||item.title||item.day||''}</h4>${item.title&&item.day?`<h5>${item.title}</h5>`:''}<p>${item.text||item.why||item.type||''}</p>${item.must?`<p><strong>Unbedingt:</strong> ${item.must}</p>`:''}${item.time?`<p><strong>Zeit:</strong> ${item.time}</p>`:''}${item.best?`<p><strong>Besonders gut für:</strong> ${item.best}</p>`:''}</article>`).join('')}</div>`}
function sourceLinks(sources){return clean(sources).map(s=>`<a href="${s.url}" target="_blank" rel="noopener">${s.name} ↗</a>`).join('')}
function detailedRoute(r,d){return `<div class="dialog-body longform"><p class="dialog-lead">${d.intro}</p><section class="decision-box"><p class="section-label">Für welche Reise ist diese Route ideal?</p><p>${d.idealFor}</p></section><section class="longform-section"><h3 class="longform-heading">Die Logik der Route</h3>${list(d.routeLogic)}</section><section class="longform-section"><h3 class="longform-heading">Die Reise Tag für Tag</h3>${cardList(d.days,'day-cards')}</section><section class="longform-section"><h3 class="longform-heading">Die Orte verstehen, bevor ihr hinfahrt</h3>${cardList(d.places,'place-cards')}</section><section class="longform-section"><h3 class="longform-heading">Incanto-Secrets</h3>${cardList(d.secrets,'secret-cards')}</section><section class="longform-section"><h3 class="longform-heading">Was ihr essen und trinken solltet</h3>${cardList(d.food,'food-cards')}</section>${clean(d.beaches).length?`<section class="longform-section"><h3 class="longform-heading">Die Strände dieser Route</h3>${cardList(d.beaches,'beach-cards')}</section>`:''}<section class="longform-section camper-planning"><h3 class="longform-heading">Mit dem Wohnmobil</h3><p>${d.camper.strategy}</p><div class="camper-grid"><article><h4>Nördliche Basis</h4><p>${d.camper.north}</p></article><article><h4>Südliche Basis</h4><p>${d.camper.south}</p></article><article><h4>Orte anfahren</h4><p>${d.camper.cityAccess}</p></article><article><h4>Komfort, der hier zählt</h4><p>${d.camper.comfort}</p></article></div></section><section class="longform-section"><h3 class="longform-heading">Was sich vor der Reise zu reservieren lohnt</h3>${list(d.bookable)}</section><section class="longform-section"><h3 class="longform-heading">So kann die Reise weitergehen</h3>${cardList(d.connections,'connection-cards')}</section><section class="source-box full-sources"><h4>Quellen und Grundlagen dieser Planung</h4>${sourceLinks(d.sources)}</section></div>`}
function editorialRoute(r){const e=r.editorial||{};return `<div class="dialog-body"><p class="dialog-lead">${r.summary}</p>${e.decision?`<section class="decision-box"><p class="section-label">Darum lohnt sich diese Route</p><p>${e.decision}</p></section>`:''}<div class="detail-grid"><div><p class="section-label">Die Route im Überblick</p><div class="stops">${r.stops.map(s=>`<span class="stop">${s}</span>`).join('')}</div>${e.highlights?`<section class="editorial-section"><h3>Was euch auf der Route erwartet</h3>${list(e.highlights)}</section>`:''}${e.taste?`<section class="editorial-section"><h3>Wein, Küche und Spezialitäten</h3>${list(e.taste)}</section>`:''}<section class="editorial-section"><h3>Besondere Abzweigungen</h3>${r.detours.map(d=>`<div class="detour"><h4>${d.title}</h4><p>${d.text}</p></div>`).join('')}</section>${e.camper?`<section class="editorial-section"><h3>Mit dem Wohnmobil</h3><p>${e.camper}</p></section>`:''}${e.connections?`<section class="editorial-section"><h3>So lässt sich die Route erweitern</h3>${list(e.connections)}</section>`:''}</div><aside><div class="source-box"><h4>Die Route in einem Satz</h4><p class="why">${e.decision||r.why}</p><h4>Quellen der Grundroute</h4><a href="${r.source.url}" target="_blank" rel="noopener">${r.source.name} ↗</a><a href="${r.source2.url}" target="_blank" rel="noopener">${r.source2.name} ↗</a></div></aside></div></div>`}
function openRoute(id){const r=routes.find(x=>x.id===id);if(!r)return;dialogContent.innerHTML=`<div class="dialog-hero" style="background-image:url('${r.image}')"><div><p class="kicker">${r.eyebrow}</p><h2>${r.title}</h2><p>${r.days} · ${r.distance}</p>${hearts(r)}</div></div>${r.details?detailedRoute(r,r.details):editorialRoute(r)}`;routeDialog.showModal();routeDialog.scrollTop=0}
function routeMatchesFilter(route,key){if(key==='all')return true;if(key==='long')return legacyTags.long.includes(route.id)||parseInt(route.days,10)>=10;const themes=route.meta?.themes||[];const water=route.meta?.water||[];const landscape=route.meta?.landscape||[];const values=[...themes,...water,...landscape];return legacyTags[key]?.includes(route.id)||themeMap[key].some(tag=>values.includes(tag))}
document.querySelector('#dialogClose').onclick=()=>routeDialog.close();routeDialog.addEventListener('click',e=>{if(e.target===routeDialog)routeDialog.close()});document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));button.classList.add('active');const key=button.dataset.filter;render(routes.filter(r=>routeMatchesFilter(r,key)))}));
const searchDialog=document.querySelector('#searchDialog'),searchInput=document.querySelector('#searchInput'),searchResults=document.querySelector('#searchResults');document.querySelector('#searchButton').onclick=()=>{searchDialog.showModal();setTimeout(()=>searchInput.focus(),100)};document.querySelector('#searchClose').onclick=()=>searchDialog.close();searchInput.addEventListener('input',()=>{const q=searchInput.value.toLowerCase().trim();if(!q){searchResults.innerHTML='';return}const found=routes.filter(r=>JSON.stringify(r).toLowerCase().includes(q));searchResults.innerHTML=found.length?found.map(r=>`<div class="search-result" data-id="${r.id}"><h3>${r.title}</h3><p>${r.region} · ${r.days}</p></div>`).join(''):'<p>Kein Treffer. Vielleicht ist genau das unsere nächste Abzweigung.</p>';document.querySelectorAll('.search-result').forEach(el=>el.onclick=()=>{searchDialog.close();openRoute(el.dataset.id)})});
const drawer=document.querySelector('#menuDrawer'),backdrop=document.querySelector('#drawerBackdrop');function toggleDrawer(open){drawer.classList.toggle('open',open);backdrop.classList.toggle('open',open);drawer.setAttribute('aria-hidden',String(!open))}document.querySelector('#menuButton').onclick=()=>toggleDrawer(true);document.querySelector('#drawerClose').onclick=()=>toggleDrawer(false);backdrop.onclick=()=>toggleDrawer(false);drawer.querySelectorAll('a').forEach(a=>a.onclick=()=>toggleDrawer(false));init().catch(()=>{grid.innerHTML='<p>Die Routen konnten nicht geladen werden.</p>'});