const ROUTE_FILES=['routes.json','routes-01-established.json','routes-02-established.json','routes-03-established.json','routes-04-established.json','routes-05-established.json'];
const STORAGE_KEY='incanto-favorites-v1';
let routes=[];
let state={version:1,projectId:'incanto-david-kay',activePerson:null,participants:{david:{favorites:{},ratings:{},rounds:[],finalists:[]},kay:{favorites:{},ratings:{},rounds:[],finalists:[]}},imports:[],updatedAt:null};
const $=selector=>document.querySelector(selector);
const personName=key=>key==='david'?'David':'Kay';
const clone=value=>JSON.parse(JSON.stringify(value));
function ensureState(raw){
 const base=clone(state);if(!raw||raw.version!==1)return base;
 base.activePerson=['david','kay'].includes(raw.activePerson)?raw.activePerson:null;
 ['david','kay'].forEach(person=>{const incoming=raw.participants?.[person]||{};base.participants[person].favorites=incoming.favorites||{};base.participants[person].ratings=incoming.ratings||{};base.participants[person].rounds=Array.isArray(incoming.rounds)?incoming.rounds:[];base.participants[person].finalists=Array.isArray(incoming.finalists)?incoming.finalists:[]});
 base.imports=Array.isArray(raw.imports)?raw.imports:[];base.updatedAt=raw.updatedAt||null;return base;
}
function loadLocal(){try{state=ensureState(JSON.parse(localStorage.getItem(STORAGE_KEY)))}catch{state=ensureState(null)}}
function save(event){state.updatedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if(event&&state.activePerson){state.imports.push({at:state.updatedAt,type:'local-change',person:state.activePerson,event});if(state.imports.length>100)state.imports=state.imports.slice(-100)}renderAll()}
function activeData(){return state.activePerson?state.participants[state.activePerson]:null}
function routeById(id){return routes.find(route=>route.id===id)}
function selectedIds(person){return Object.keys(state.participants[person].favorites||{})}
function combinedIds(){return [...new Set([...selectedIds('david'),...selectedIds('kay')])]}
function remainingIds(person){const combined=combinedIds();const eliminated=new Set((state.participants[person].rounds||[]).flatMap(round=>round.eliminated||[]));return combined.filter(id=>!eliminated.has(id))}
function renderIdentity(){document.querySelectorAll('[data-person]').forEach(button=>button.classList.toggle('active',button.dataset.person===state.activePerson));$('#activePerson').textContent=state.activePerson?`${personName(state.activePerson)} arbeitet gerade. Änderungen werden automatisch auf diesem Gerät gespeichert.`:'Noch keine Person gewählt.'}
function routeCard(route){const data=activeData();const favorite=data?.favorites?.[route.id];const disabled=!favorite&&selectedIds(state.activePerson||'david').length>=4;return `<article class="route-card ${favorite?'selected':''}"><img src="${route.image}" alt=""><div class="route-copy"><span class="route-meta">${route.region} · ${route.days}</span><h3>${route.title}</h3><p>${route.summary}</p><button type="button" data-toggle-route="${route.id}" ${!state.activePerson||disabled?'disabled':''}>${favorite?'Auswahl entfernen':'Route auswählen'}</button>${favorite?`<textarea data-reason="${route.id}" placeholder="Was reizt dich an dieser Route? Ein kurzer Gedanke hilft ${state.activePerson==='david'?'Kay':'David'}, deine Auswahl später zu verstehen.">${favorite.reason||''}</textarea>`:''}<a href="index.html?route=${encodeURIComponent(route.id)}#routes">Route vollständig lesen →</a></div></article>`}
function renderPicker(){const count=state.activePerson?selectedIds(state.activePerson).length:0;$('#selectionCount').textContent=`${count} / 4`;$('#routePicker').innerHTML=routes.map(routeCard).join('');document.querySelectorAll('[data-toggle-route]').forEach(button=>button.onclick=()=>toggleFavorite(button.dataset.toggleRoute));document.querySelectorAll('[data-reason]').forEach(field=>field.onchange=()=>{activeData().favorites[field.dataset.reason].reason=field.value.trim();save('Begründung geändert')})}
function toggleFavorite(id){if(!state.activePerson)return;const data=activeData();if(data.favorites[id])delete data.favorites[id];else{if(selectedIds(state.activePerson).length>=4)return;data.favorites[id]={reason:'',selectedAt:new Date().toISOString()}}data.rounds=[];data.finalists=[];save('Grundauswahl geändert')}
function combinedCard(id){const route=routeById(id);if(!route)return'';const d=state.participants.david.favorites[id];const k=state.participants.kay.favorites[id];return `<article class="combined-card"><img src="${route.image}" alt=""><div class="combined-copy"><div class="choice-badges">${d&&k?'<span class="badge both">von beiden gewählt</span>':''}${d?'<span class="badge">David</span>':''}${k?'<span class="badge">Kay</span>':''}</div><h3>${route.title}</h3><p class="route-meta">${route.region} · ${route.days}</p>${d?.reason?`<p class="reason"><strong>David:</strong> ${d.reason}</p>`:''}${k?.reason?`<p class="reason"><strong>Kay:</strong> ${k.reason}</p>`:''}<a href="index.html?route=${encodeURIComponent(route.id)}#routes">Karte und Details öffnen →</a></div></article>`}
function renderCombined(){const ids=combinedIds();$('#combinedCount').textContent=ids.length?`${ids.length} unterschiedliche Route${ids.length===1?'':'n'}`:'';$('#combinedRoutes').className=ids.length?'combined-routes':'combined-routes empty-state';$('#combinedRoutes').innerHTML=ids.length?ids.map(combinedCard).join(''):'Lade die Auswahl des anderen hoch, sobald sie vorliegt.'}
function renderRanking(){const ids=combinedIds(),data=activeData();if(!state.activePerson||ids.length<2){$('#rankingRoutes').className='ranking-routes empty-state';$('#rankingRoutes').textContent='Wähle zuerst eine Person und führe mindestens zwei unterschiedliche Routen zusammen.';return}$('#rankingRoutes').className='ranking-routes';$('#rankingRoutes').innerHTML=ids.map(id=>{const route=routeById(id),rating=Number(data.ratings[id]||0);return `<article class="rank-card"><div><span class="route-meta">${route.region}</span><h3>${route.title}</h3></div><div class="rating" aria-label="Bewertung für ${route.title}">${[1,2,3,4,5].map(n=>`<button type="button" class="${rating===n?'active':''}" data-rate="${id}" data-value="${n}">${n}</button>`).join('')}</div></article>`}).join('');document.querySelectorAll('[data-rate]').forEach(button=>button.onclick=()=>{data.ratings[button.dataset.rate]=Number(button.dataset.value);save('Bewertung geändert')})}
function renderRounds(){const ids=combinedIds(),data=activeData();if(!state.activePerson||ids.length<2){$('#activeRound').className='active-round empty-state';$('#activeRound').textContent='Die Ausscheidungsrunde beginnt nach dem Zusammenführen von mindestens zwei Routen.';$('#roundHistory').innerHTML='';renderFinalists();return}const remaining=remainingIds(state.activePerson);const finished=remaining.length<=2;$('#activeRound').className='active-round';$('#activeRound').innerHTML=finished?`<p>Deine persönliche Auswahl ist auf ${remaining.length} Finalist${remaining.length===1?'en':'en'} reduziert.</p><div class="round-actions"><button type="button" id="setFinalists">Als Finalisten festlegen</button>${data.rounds.length?'<button type="button" id="undoRound">Letzte Runde zurücknehmen</button>':''}</div>`:`<div class="round-grid">${remaining.map(id=>{const route=routeById(id);return `<article class="round-card"><label><input type="checkbox" data-eliminate="${id}"><span><span class="route-meta">${route.region}</span><h3>${route.title}</h3><small>Diese Route in der nächsten Runde loslassen</small></span></label></article>`}).join('')}</div><div class="round-actions"><button type="button" id="saveRound">Ausgewählte Routen aussortieren</button>${data.rounds.length?'<button type="button" id="undoRound">Letzte Runde zurücknehmen</button>':''}</div><p class="status-line">Pro Runde höchstens zwei. Mindestens eine Route muss im Rennen bleiben.</p>`;
 $('#saveRound')?.addEventListener('click',saveRound);$('#undoRound')?.addEventListener('click',()=>{data.rounds.pop();data.finalists=[];save('Letzte Ausscheidungsrunde zurückgenommen')});$('#setFinalists')?.addEventListener('click',()=>{data.finalists=remaining;save('Finalisten festgelegt')});
 $('#roundHistory').innerHTML=data.rounds.length?`<h3>Historie</h3>${data.rounds.map((round,index)=>`<article class="history-entry"><h4>Runde ${index+1}</h4><p>Ausgeschieden: ${(round.eliminated||[]).map(id=>routeById(id)?.title||id).join(', ')}</p><small>${new Date(round.at).toLocaleString('de-DE')}</small></article>`).join('')}`:'';renderFinalists()}
function saveRound(){const data=activeData(),remaining=remainingIds(state.activePerson);const chosen=[...document.querySelectorAll('[data-eliminate]:checked')].map(input=>input.dataset.eliminate);if(!chosen.length||chosen.length>2||remaining.length-chosen.length<1){alert('Bitte eine oder zwei Routen auswählen. Mindestens eine Route muss übrig bleiben.');return}data.rounds.push({at:new Date().toISOString(),before:remaining,eliminated:chosen,after:remaining.filter(id=>!chosen.includes(id))});data.finalists=[];save('Ausscheidungsrunde gespeichert')}
function renderFinalists(){const data=activeData();if(!data||!data.finalists.length){$('#finalists').className='finalists empty-state';$('#finalists').textContent='Noch keine Finalisten festgelegt.';return}$('#finalists').className='finalists';$('#finalists').innerHTML=data.finalists.map(combinedCard).join('')}
function renderAll(){renderIdentity();renderPicker();renderCombined();renderRanking();renderRounds()}
function exportState(){const filename=`incanto-${state.activePerson||'stand'}-${new Date().toISOString().slice(0,10)}.json`;const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url);$('#fileStatus').textContent=`${filename} wurde erstellt.`}
function mergeImported(imported){const clean=ensureState(imported);['david','kay'].forEach(person=>{const incoming=clean.participants[person],current=state.participants[person];if(Object.keys(incoming.favorites).length)current.favorites=incoming.favorites;if(Object.keys(incoming.ratings).length)current.ratings={...current.ratings,...incoming.ratings};if(incoming.rounds.length>=current.rounds.length)current.rounds=incoming.rounds;if(incoming.finalists.length)current.finalists=incoming.finalists});state.imports.push({at:new Date().toISOString(),type:'json-import',sourceUpdatedAt:clean.updatedAt||null});save('JSON-Datei importiert')}
async function importState(file){try{const parsed=JSON.parse(await file.text());if(parsed.version!==1||parsed.projectId!=='incanto-david-kay')throw new Error('Diese Datei gehört nicht zum Incanto-Auswahlprojekt.');mergeImported(parsed);$('#fileStatus').textContent='Die Datei wurde eingelesen. Eigene und fremde Auswahl sind jetzt zusammengeführt.'}catch(error){$('#fileStatus').textContent=`Import nicht möglich: ${error.message}`}}
async function init(){loadLocal();const responses=await Promise.all(ROUTE_FILES.map(file=>fetch(file)));const blocks=await Promise.all(responses.map(response=>response.ok?response.json():[]));routes=blocks.flat();document.querySelectorAll('[data-person]').forEach(button=>button.onclick=()=>{state.activePerson=button.dataset.person;save('Person gewechselt')});$('#exportState').onclick=exportState;$('#importState').onchange=event=>{const file=event.target.files?.[0];if(file)importState(file);event.target.value=''};renderAll()}
init().catch(error=>{$('#routePicker').innerHTML=`<p>Die Routen konnten nicht geladen werden: ${error.message}</p>`});